networks:
  application:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - DB_HOST=mypgdb
    networks:
      - application
    # entrypoint: ['/bin/sh', '-c']
    command: >
      /bin/sh -c "
      composer install &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-db
    networks:
      - application
    container_name: mypgdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
